// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auadfaboxudeeklegaie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1YWRmYWJveHVkZWVrbGVnYWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MDUyMzUsImV4cCI6MjA4OTI4MTIzNX0.vJ6h9xXUkgrpAH1TG2sApy6uTVloDnWGr2AnFDXswko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});